///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package sys_user_model

import (
	"fmt"
	"time"

	"github.com/unhejing/go-gin-api/utils/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *SysUser {
	return new(SysUser)
}

func NewQueryBuilder() *sysUserModelQueryBuilder {
	return new(sysUserModelQueryBuilder)
}

func (t *SysUser) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type sysUserModelQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *sysUserModelQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *sysUserModelQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&SysUser{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *sysUserModelQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&SysUser{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *sysUserModelQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&SysUser{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *sysUserModelQueryBuilder) First(db *gorm.DB) (*SysUser, error) {
	ret := &SysUser{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *sysUserModelQueryBuilder) QueryOne(db *gorm.DB) (*SysUser, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *sysUserModelQueryBuilder) QueryAll(db *gorm.DB) ([]*SysUser, error) {
	var ret []*SysUser
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *sysUserModelQueryBuilder) Limit(limit int) *sysUserModelQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *sysUserModelQueryBuilder) Offset(offset int) *sysUserModelQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereId(p mysql.Predicate, value int32) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereIdIn(value []int32) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereIdNotIn(value []int32) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) OrderById(asc bool) *sysUserModelQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereUsername(p mysql.Predicate, value string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "username", p),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereUsernameIn(value []string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "username", "IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereUsernameNotIn(value []string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "username", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) OrderByUsername(asc bool) *sysUserModelQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "username "+order)
	return qb
}

func (qb *sysUserModelQueryBuilder) WherePassword(p mysql.Predicate, value string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "password", p),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WherePasswordIn(value []string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "password", "IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WherePasswordNotIn(value []string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "password", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) OrderByPassword(asc bool) *sysUserModelQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "password "+order)
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereNickname(p mysql.Predicate, value string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "nickname", p),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereNicknameIn(value []string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "nickname", "IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereNicknameNotIn(value []string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "nickname", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) OrderByNickname(asc bool) *sysUserModelQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "nickname "+order)
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereMobile(p mysql.Predicate, value string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "mobile", p),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereMobileIn(value []string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "mobile", "IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereMobileNotIn(value []string) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "mobile", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) OrderByMobile(asc bool) *sysUserModelQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "mobile "+order)
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereIsUsed(p mysql.Predicate, value int32) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_used", p),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereIsUsedIn(value []int32) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_used", "IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereIsUsedNotIn(value []int32) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_used", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) OrderByIsUsed(asc bool) *sysUserModelQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_used "+order)
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereIsDeleted(p mysql.Predicate, value int32) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_deleted", p),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereIsDeletedIn(value []int32) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_deleted", "IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereIsDeletedNotIn(value []int32) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_deleted", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) OrderByIsDeleted(asc bool) *sysUserModelQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_deleted "+order)
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereCreatedTime(p mysql.Predicate, value time.Time) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_time", p),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereCreatedTimeIn(value []time.Time) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_time", "IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereCreatedTimeNotIn(value []time.Time) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) OrderByCreatedTime(asc bool) *sysUserModelQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_time "+order)
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereUpdatedTime(p mysql.Predicate, value time.Time) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_time", p),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereUpdatedTimeIn(value []time.Time) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_time", "IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) WhereUpdatedTimeNotIn(value []time.Time) *sysUserModelQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sysUserModelQueryBuilder) OrderByUpdatedTime(asc bool) *sysUserModelQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_time "+order)
	return qb
}
