definitions:
  code.Failure:
    properties:
      code:
        description: 业务码
        type: integer
      message:
        description: 描述信息
        type: string
    type: object
  request.IdRequest:
    properties:
      id:
        description: 主键ID
        type: integer
    type: object
  response.Result:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  sys_config_dto.PageReq:
    properties:
      page:
        description: 第几页
        type: integer
      size:
        description: 每页显示条数
        type: integer
    type: object
  sys_config_model.SysConfig:
    properties:
      channel_tag:
        description: 渠道标签
        type: string
      created_time:
        description: 创建时间
        type: string
      id:
        description: id
        type: integer
      note:
        description: 备注
        type: string
      params_key:
        description: 参数键名
        type: string
      params_name:
        description: 参数名称
        type: string
      params_value:
        description: 参数键值
        type: string
      updated_time:
        description: 更新时间
        type: string
    type: object
  sys_user_dto.LoginReq:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  sys_user_dto.PageReq:
    properties:
      page:
        description: 第几页
        type: integer
      size:
        description: 每页显示条数
        type: integer
    type: object
  sys_user_dto.RegisterReq:
    properties:
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 昵称
        type: string
      password:
        description: MD5后的密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - mobile
    - nickname
    - password
    - username
    type: object
info:
  contact: {}
  title: swagger 接口文档
  version: "2.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 登录信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/sys_user_dto.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginToken: []
      summary: 用户登录
      tags:
      - API.sys_user_dto
  /api/sys_config/add:
    post:
      consumes:
      - application/json
      description: 新增
      parameters:
      - description: 请求信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/sys_config_model.SysConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginToken: []
      summary: 新增
      tags:
      - API.sys_config
  /api/sys_config/delete:
    post:
      consumes:
      - application/json
      description: 删除
      parameters:
      - description: 请求实体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.IdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginToken: []
      summary: 删除
      tags:
      - API.sys_config
  /api/sys_config/edit:
    post:
      consumes:
      - application/json
      description: 编辑
      parameters:
      - description: 请求信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/sys_config_model.SysConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginToken: []
      summary: 编辑
      tags:
      - API.sys_config
  /api/sys_config/pageList:
    post:
      consumes:
      - application/json
      description: 分页查询
      parameters:
      - description: 请求信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/sys_config_dto.PageReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginToken: []
      summary: 分页查询
      tags:
      - API.sys_config
  /api/sys_user_dto/delete:
    post:
      consumes:
      - application/json
      description: 删除
      parameters:
      - description: 请求实体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.IdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginToken: []
      summary: 删除
      tags:
      - API.sys_user_dto
  /api/sys_user_dto/pageList:
    post:
      consumes:
      - application/json
      description: 分页查询
      parameters:
      - description: 请求信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/sys_user_dto.PageReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginToken: []
      summary: 分页查询
      tags:
      - API.sys_user_dto
  /api/sys_user_dto/register:
    post:
      consumes:
      - application/json
      description: 新增用户
      parameters:
      - description: 用户信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/sys_user_dto.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginToken: []
      summary: 新增用户
      tags:
      - API.sys_user_dto
securityDefinitions:
  LoginToken:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
